### PR TITLE
Use meta, not metacorpus

### PR DESCRIPTION
**Pull request by kbenoit**
We're killing off `metacorpus()` in the forthcoming quanteda v3. This works with v2.1.2 already since `meta()` has been around for a while.

### CODE REVIEW

**Comment by kbenoit** [comment]
@JBGruber I added another deprecation fix, to avoid warnings: We are now encouraging users to tokenise a character or corpus input before calling `dfm()`. We're also simplifying the arguments to `dfm()`.

I made a slight tweak in your code to avoid the warnings in 536f02c. It will still work fine with the 2.1.2 version of quanteda currently on CRAN.

I'm not sure why this test is failing but it does not seem related to **quanteda**. 

```
Failure (test-lnt_convert.R:152:3): Convert LNToutput to SQLite
{
    ...
} not equal to readRDS("../files/SQLite.RDS").
Attributes: < Names: 5 string mismatches >
Attributes: < Length mismatch: comparison on first 8 components >
Attributes: < Component 4: Modes: logical, numeric >
Attributes: < Component 4: target is logical, current is numeric >
Attributes: < Component 5: Modes: numeric, logical >
Attributes: < Component 5: target is numeric, current is logical >
Attributes: < Component 6: Modes: logical, externalptr >
Attributes: < Component 6: target is logical, current is externalptr >
Attributes: < Component 7: 'target' is not an environment >
...
```

**Comment by JBGruber** [comment]
Thanks again! The tests work fine locally. For some reason all the convert functions are a huge hassle to maintain on CI. I only recently switched to GitHub actions and think I have to make the tests a bit more lenient.

**Comment by JBGruber** [comment]
And sorry for the slow reaction, I didn't see the PR until this morning.

**Comment by kbenoit** [comment]
Thanks! No problem at all.

**Pull request merged**
